[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "docs/.vitepress/dist"
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

